// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Wcw25gYHFmX8-2ksk973fYS_eY2xdUA',
    appId: '1:661972065953:web:88168ead1499d446719ae0',
    messagingSenderId: '661972065953',
    projectId: 'purno-7e189',
    authDomain: 'purno-7e189.firebaseapp.com',
    storageBucket: 'purno-7e189.firebasestorage.app',
    measurementId: 'G-R8D6PSSKDL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Q8RozZX5hcwT8En29UN0y3OixfIN1TM',
    appId: '1:661972065953:android:398e4f10e05c5990719ae0',
    messagingSenderId: '661972065953',
    projectId: 'purno-7e189',
    storageBucket: 'purno-7e189.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByELDV-zAgSeGZUfNsY8GDEaiImZcAv8M',
    appId: '1:661972065953:ios:5d642e8b62964883719ae0',
    messagingSenderId: '661972065953',
    projectId: 'purno-7e189',
    storageBucket: 'purno-7e189.firebasestorage.app',
    iosBundleId: 'com.example.purnomerchant',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByELDV-zAgSeGZUfNsY8GDEaiImZcAv8M',
    appId: '1:661972065953:ios:5d642e8b62964883719ae0',
    messagingSenderId: '661972065953',
    projectId: 'purno-7e189',
    storageBucket: 'purno-7e189.firebasestorage.app',
    iosBundleId: 'com.example.purnomerchant',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Wcw25gYHFmX8-2ksk973fYS_eY2xdUA',
    appId: '1:661972065953:web:f883133cd769931d719ae0',
    messagingSenderId: '661972065953',
    projectId: 'purno-7e189',
    authDomain: 'purno-7e189.firebaseapp.com',
    storageBucket: 'purno-7e189.firebasestorage.app',
    measurementId: 'G-4HXX0B1TN0',
  );
}
